packages:
  - "."
  - "legacis_dashboard"

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - canvas
  - prisma
  - sharp

# pnpm configuration for hoisting
public-hoist-pattern:
  - "pdfjs-dist"