ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - canvas
  - prisma
  - sharp
  - unrs-resolver

packages:
  - 'legacis_dashboard'
  - '.'