ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - canvas
  - prisma
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - canvas
  - core-js
  - prisma
  - sharp
  - unrs-resolver
