import type { Metadata } from "next";
import { Poppins , Urbanist} from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/components/reduxStateProvider";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner"
import Nav from "@/components/nav";
import { Authentication } from "@/components/auth/authentication";
import { SessionProvider } from "next-auth/react";
import Modal from "@/components/profile/modal";
import Script from "next/script";

const poppins = Poppins({
   weight : [ "100", "200", "300", "400", "500", "600", "700", "800", "900"],
   variable: "--font-poppins",
   subsets: ["latin"],
});

const urbanist = Urbanist({
  weight: ["400", "500", "600", "700"],
  variable: "--font-urbanist",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Legacis",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} ${urbanist.variable} antialiased overflow-x-clip relative`}
      >
         <ThemeProvider 
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            >
           <SessionProvider> 
            <ReduxProvider>
               <Authentication />
               <Modal />
               <Nav />
               {children}
               <Toaster />
            </ReduxProvider>
          </SessionProvider>
         </ThemeProvider>

      </body>
    </html>
  );
}
