import type { Metadata } from "next";
import "../globals.css";
import Modal from "@/components/profile/modal";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "./(components)/app-sidebar";
import { Session } from "@/actions/session";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
  title: "Legacis",
  description: "Generated by create next app",
};

export default async function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await Session();
  if (!session) {
    notFound();
  }
  if (session?.user?.role !== "ADMIN") {
    notFound();
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <SidebarProvider className="mt-24">
          <AppSidebar />
          <SidebarTrigger />
          {children}
        </SidebarProvider>
      </body>
    </html>
  );
}
